

const NewsData = () => {
    return ([
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Actualidad"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Destacados"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Destacados"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Destacados"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Electricidad"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Electricidad"
        },
        {
            title: "Codelco digitaliza y moderniza su red eléctrica con MicroSCADA de Hitachi Energy",
            resume: "El acceso remoto a la red eléctrica facilita la detección en tiempo real y la resolución oportuna de fallas.",
            date: "30 diciembre 2021",
            image: "",
            info: `Codelco, la empresa minera estatal de cobre de Chile, quiere extender la vida útil de su mina Andes Norte (División El Teniente). Con actividades mineras que se remontan a 1819, la mina El Teniente ha sido explotada desde 1905 y es la mina subterránea de cobre más grande del mundo. 
                    Como parte del impulso de Codelco por reducir su huella de carbono e impulsar la sostenibilidad, la compañía busca actualizar y modernizar su sistema de automatización de energía en El Teniente. El objetivo es asegurar la continuidad operativa de la mina en un área mineralizada a 300 metros por debajo del nivel minero actual y extender la vida útil de la mina en cerca de 50 años. ${<br />}
                    Para lograr esto, Codelco tuvo que instalar un nuevo sistema de control de supervisión y adquisición de datos (SCADA) para administrar la red eléctrica dentro de la mina. Llevando esto más allá, la compañía buscó ampliar la funcionalidad del sistema desplegando la solución de manera centralizada en su nuevo centro de datos en la ciudad de Rancagua, ubicada a 70 kilómetros de la mina. El objetivo era vincular las divisiones de la compañía, comenzando con El Teniente, con el centro de datos para administrar centralmente las redes eléctricas de los proyectos gemelos relacionados con Andes Norte. ${<br />}
                    Codelco eligió la solución avanzada MicroSCADA X de Hitachi Energy para controlar y administrar la red eléctrica que comprende 27 subestaciones eléctricas en El Teniente; siete de ellas ubicadas en la superficie y 20 dentro de la mina. Con MicroSCADA X, Codelco tendrá un mejor acceso a la información virtualizada y permitirá un sistema más seguro para almacenar datos estratégicos. ${<br />}
                    'Estamos implementando la última tecnología en El Teniente, lo que nos da la tranquilidad de extender nuestras operaciones hacia el futuro, al darle a la mina otros 50 años de vida productiva', dijo Marcos Recio Moya, gerente de puesta en marcha del proyecto Andes Norte Nuevo Nivel Mina en la División El Teniente de Codelco. Añadió: 'También queremos ir más allá, centralizando el funcionamiento de todo el sistema SCADA desde el centro de datos, y la propuesta de Hitachi Energy cumplió mejor con lo que buscábamos en términos de su fiabilidad, respaldo, soporte y costo'.  ${<br />}
                    MicroSCADA X es una solución de automatización de energía centrada en el usuario, que proporciona una experiencia moderna e intuitiva. El innovador despliegue centralizado del sistema SCADA proporciona acceso remoto a la red eléctrica, facilitando la detección de fallas y la resolución de problemas en tiempo real, digitalizando así la red eléctrica de El Teniente.  ${<br />}
                    Como parte de la solución, Hitachi Energy proporcionará ingeniería, unidades terminales remotas, suministros de gabinetes, actualización del sistema SCADA eléctrico existente y operación, además de un contrato de cinco años para mantener los sistemas en El Teniente. ${<br />}
                    Con la implementación iniciada en 2021, se espera que el proyecto esté completamente en marcha para 2024.`,
            type: "Electricidad"
        },
    ])
}

export default NewsData